#!/usr/bin/env npx tsx
/**
 * Refresh `backend/src/generated/oracle-pool-configs.ts` from
 * @aave-dao/aave-address-book.
 *
 * Populates V3 pool configs (poolAddress + oracleAddress) from AaveV3* exports,
 * and V4 spoke configs (spokeAddress + oracleAddress) from AaveV4Ethereum SPOKES.
 *
 * Usage:
 *   npm run sync:oracle-pool-configs
 *   npm run sync:oracle-pool-configs -- --check   # exit 1 if file would change
 */
import * as addressBook from '@aave-dao/aave-address-book';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface SyncedV3PoolConfig {
  poolKey: string;
  chainId: number;
  poolAddress: string;
  oracleAddress: string;
}

interface SyncedV4SpokeConfig {
  spokeName: string;
  chainId: number;
  spokeAddress: string;
  oracleAddress: string;
}

const EXCLUDED_POOLS = new Set([
  'AaveV3ArbitrumSepolia',
  'AaveV3BaseSepolia',
  'AaveV3BaseSepoliaLido',
  'AaveV3Fuji',
  'AaveV3Fantom',
  'AaveV3FantomTestnet',
  'AaveV3InkSepolia',
  'AaveV3OptimismSepolia',
  'AaveV3ScrollSepolia',
  'AaveV3Sepolia',
]);

function getAaveV3MainnetPoolConfigs(): SyncedV3PoolConfig[] {
  const names = Object.keys(addressBook).filter(
    (key) => key.startsWith('AaveV3') && !EXCLUDED_POOLS.has(key),
  );
  const configs: SyncedV3PoolConfig[] = [];
  for (const name of names) {
    const net = (addressBook as Record<string, { CHAIN_ID?: number; POOL?: string; ORACLE?: string }>)[name];
    if (!net || typeof net.CHAIN_ID !== 'number' || !net.POOL || !net.ORACLE) continue;
    configs.push({
      poolKey: name,
      chainId: net.CHAIN_ID,
      poolAddress: net.POOL.toLowerCase(),
      oracleAddress: net.ORACLE.toLowerCase(),
    });
  }
  configs.sort((a, b) => {
    if (a.chainId !== b.chainId) return a.chainId - b.chainId;
    return a.poolKey.localeCompare(b.poolKey);
  });
  return configs;
}

function spokeKeyToName(key: string): string {
  // Strip _SPOKE / _ESPOKE suffix, keep Correlated/Ecosystem/etc as part of the name
  const base = key.replace(/_E?SPOKE$/, '');
  return base.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).replace(/ /g, '');
}

function getAaveV4SpokeConfigs(): SyncedV4SpokeConfig[] {
  const v4 = (addressBook as Record<string, { CHAIN_ID?: number; SPOKES?: Record<string, string> }>).AaveV4Ethereum;
  if (!v4 || !v4.SPOKES) return [];

  const spokes = v4.SPOKES;
  const configs: SyncedV4SpokeConfig[] = [];
  const seen = new Set<string>();

  // First pass: collect all spoke→oracle pairs
  const spokeEntries: Array<{ key: string; spokeAddr: string; oracleAddr: string | undefined }> = [];
  const oracleMap: Record<string, string> = {};
  for (const key of Object.keys(spokes)) {
    if (!key.endsWith('_SPOKE') && !key.endsWith('_ESPOKE')) continue;
    const oracleKey = key + '_ORACLE';
    const oracleAddr = spokes[oracleKey];
    if (oracleAddr) oracleMap[key] = oracleAddr;
    spokeEntries.push({ key, spokeAddr: spokes[key], oracleAddr });
  }

  // Attach oracles where available, skip spokes without oracle
  for (const { key, spokeAddr, oracleAddr } of spokeEntries) {
    const oracle = oracleAddr ?? oracleMap[key];
    if (!oracle) continue;

    const spokeName = spokeKeyToName(key);
    if (seen.has(spokeName)) continue;
    seen.add(spokeName);

    configs.push({
      spokeName,
      chainId: v4.CHAIN_ID ?? 1,
      spokeAddress: spokeAddr.toLowerCase(),
      oracleAddress: oracle.toLowerCase(),
    });
  }

  configs.sort((a, b) => a.spokeName.localeCompare(b.spokeName));
  return configs;
}

function renderGeneratedTs(v3: SyncedV3PoolConfig[], v4: SyncedV4SpokeConfig[]): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated by `npm run sync:oracle-pool-configs` — do not edit by hand.',
    ' * Source: @aave-dao/aave-address-book',
    ' */',
    '',
    'export interface SyncedV3PoolConfig {',
    '  poolKey: string;',
    '  chainId: number;',
    '  poolAddress: string;',
    '  oracleAddress: string;',
    '}',
    '',
    'export interface SyncedV4SpokeConfig {',
    '  spokeName: string;',
    '  chainId: number;',
    '  spokeAddress: string;',
    '  oracleAddress: string;',
    '}',
    '',
    'export const SYNCED_V3_POOL_CONFIGS: SyncedV3PoolConfig[] = [',
  ];
  for (const c of v3) {
    lines.push(
      `  { poolKey: '${c.poolKey}', chainId: ${c.chainId}, poolAddress: '${c.poolAddress}', oracleAddress: '${c.oracleAddress}' },`,
    );
  }
  lines.push('];', '', 'export const SYNCED_V4_SPOKE_CONFIGS: SyncedV4SpokeConfig[] = [');
  for (const c of v4) {
    lines.push(
      `  { spokeName: '${c.spokeName}', chainId: ${c.chainId}, spokeAddress: '${c.spokeAddress}', oracleAddress: '${c.oracleAddress}' },`,
    );
  }
  lines.push('];');
  return lines.join('\n') + '\n';
}

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(rootDir, 'backend', 'src', 'generated', 'oracle-pool-configs.ts');

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const v3 = getAaveV3MainnetPoolConfigs();
  const v4 = getAaveV4SpokeConfigs();
  const content = renderGeneratedTs(v3, v4);

  if (checkOnly) {
    let existing = '';
    try {
      existing = await readFile(outPath, 'utf8');
    } catch {
      existing = '';
    }
    if (existing !== content) {
      console.error('[sync-oracle-pool-configs] --check failed: file is stale or missing');
      process.exitCode = 1;
    } else {
      console.log('[sync-oracle-pool-configs] --check ok');
    }
    return;
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, content, 'utf8');
  console.log(`[sync-oracle-pool-configs] wrote ${outPath} (${v3.length} V3 pools, ${v4.length} V4 spokes)`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});