#!/usr/bin/env npx tsx
/**
 * Refresh `src/generated/coingecko-platform-by-chain-id.ts` from CoinGecko
 * `/api/v3/asset_platforms`, filtered to Aave V3 mainnet networks in
 * `@bgd-labs/aave-address-book` (same filter as `getAllAaveV3NetworksFromAddressBook`).
 *
 * Usage:
 *   npm run sync:coingecko-platform-map
 *   npm run sync:coingecko-platform-map -- --check   # exit 1 if file would change
 */
import * as addressBook from '@aave-dao/aave-address-book';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const COINGECKO_ASSET_PLATFORMS = 'https://api.coingecko.com/api/v3/asset_platforms';

type AssetPlatform = { id?: string; chain_identifier?: number | null };

function getAaveV3MainnetChainIds(): number[] {
  const names = Object.keys(addressBook).filter(
    (key) => key.startsWith('AaveV3') && !key.includes('Sepolia') && !key.includes('Fuji'),
  );
  const ids = new Set<number>();
  for (const name of names) {
    const network = (addressBook as Record<string, { CHAIN_ID?: number }>)[name];
    const chainId = network?.CHAIN_ID;
    if (typeof chainId === 'number' && Number.isFinite(chainId) && chainId > 0) {
      ids.add(chainId);
    }
  }
  return [...ids].sort((a, b) => a - b);
}

async function fetchAssetPlatformMap(): Promise<Map<number, string>> {
  const response = await fetch(COINGECKO_ASSET_PLATFORMS);
  if (!response.ok) {
    throw new Error(`CoinGecko /asset_platforms failed (${response.status})`);
  }
  const payload = (await response.json()) as AssetPlatform[];
  const map = new Map<number, string>();
  if (!Array.isArray(payload)) return map;
  for (const item of payload) {
    const chainId = item.chain_identifier;
    const platformId = item.id;
    if (
      typeof chainId === 'number' &&
      Number.isFinite(chainId) &&
      chainId > 0 &&
      typeof platformId === 'string' &&
      platformId.trim() !== ''
    ) {
      map.set(chainId, platformId);
    }
  }
  return map;
}

function renderGeneratedTs(chainIdToPlatform: Map<number, string>): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated by `npm run sync:coingecko-platform-map` — do not edit by hand.',
    ` * Source: ${COINGECKO_ASSET_PLATFORMS}`,
    ' */',
    '',
    'export const COINGECKO_PLATFORM_BY_CHAIN_ID_SYNCED: Record<number, string> = {',
  ];
  const sortedIds = [...chainIdToPlatform.keys()].sort((a, b) => a - b);
  for (const id of sortedIds) {
    const platform = chainIdToPlatform.get(id)!;
    const escaped = platform.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    lines.push(`  ${id}: '${escaped}',`);
  }
  lines.push('};', '');
  return lines.join('\n');
}

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(rootDir, 'src', 'generated', 'coingecko-platform-by-chain-id.ts');

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const targetChainIds = getAaveV3MainnetChainIds();
  const apiMap = await fetchAssetPlatformMap();

  const resolved = new Map<number, string>();
  const missing: number[] = [];
  for (const chainId of targetChainIds) {
    const platformId = apiMap.get(chainId);
    if (platformId) {
      resolved.set(chainId, platformId);
    } else {
      missing.push(chainId);
    }
  }

  if (missing.length > 0) {
    console.warn(
      '[sync-coingecko-platform-map] No CoinGecko platform id for chain(s):',
      missing.join(', '),
    );
    console.warn(
      '[sync-coingecko-platform-map] Add a manual override in token-price-resolver.ts if needed.',
    );
  }

  const content = renderGeneratedTs(resolved);

  if (checkOnly) {
    let existing = '';
    try {
      existing = await readFile(outPath, 'utf8');
    } catch {
      existing = '';
    }
    if (existing !== content) {
      console.error('[sync-coingecko-platform-map] --check failed: file is stale or missing');
      process.exitCode = 1;
    } else {
      console.log('[sync-coingecko-platform-map] --check ok');
    }
    return;
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, content, 'utf8');
  console.log(`[sync-coingecko-platform-map] wrote ${outPath} (${resolved.size} chains)`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
